
import '../styles/global.css';
import Navbar from "@/components/Navbar/Navbar";
// import image from "../assets/background.png"
import Footer from "@/components/Footer/Footer";


// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
   
      <body>
        <div className="p-5  h-[300px]" >
        <Navbar/>
        {children}
        <Footer/>
      </div></body>
    </html>
  );
}
